{% set version = "0.4" %}

package:
  name: pygeos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeos/pygeos-{{ version }}.tar.gz
  sha256: 4b7f4a6600d47db8d48aa251c365c260c3ad163f4ae4a382ce32c67ad34ffee1
  patches:
    # already fixed upstream, drop when a new version is available
    - inc_lib_path.patch

build:
  number: 0
  skip: True  # [win or py2k]
  script:
    # already fixed upstream, drop when a new version is available
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - export GEOS_INCLUDE_PATH=${PREFIX}/include  # [not win]
    - export GEOS_LIBRARY_PATH=${PREFIX}/lib  # [not win]
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos

test:
  imports:
    - pygeos

about:
  home: https://github.com/caspervdw/pygeos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Wraps GEOS geometry functions in numpy ufuncs'

  description: |
    PyGEOS is a C/Python library with vectorized geometry functions.
    The geometry operations are done in the open-source geometry library GEOS.
    PyGEOS wraps these operations in NumPy ufuncs providing a performance
    improvement when operating on arrays of geometries.
  doc_url: https://pygeos.readthedocs.io/en/latest/
  dev_url: https://github.com/caspervdw/pygeos

extra:
  recipe-maintainers:
    - caspervdw
    - jorisvandenbossche
