travis:
  secure:
    BINSTAR_TOKEN: kIeT7Im+9dM5jY+QglHfIVkyeJCV1I/cKtsYW3jLPMepeXi/sPv73SbOcUp3lXq80exkl2cYIGr1rTSR0IVH5N6xyHkS7/BPyt5DK91ZZTgR4fVpQOyZFwhh+VO28pphFwhEOAEqLMG4O5TtPJouJ4nzQrpPJq+rTKmvjfk4olVIOR6lHny/jzbNlLK/gDhjyBHVd6eoK94fFavasmu2AgWVeyFIM9je0aY7iYd1wNaMV3zSS/nkDBLtVTHs7P4NdiBsc/pyG4rXZiH+W1I3V4dHMdXFdF7KPNOZFExfqZy5ApHSvVgwXctONkZ1nsX9ykIOjclhVy78q0KNDLGl1vL74QPNzVgeWj5yJHkRoMMyn17BnyqBToufZE+TlsTGicMv+a2oMRYAfV6tII2THl+AQlAg4dtU/s6YGuc+W9zS/WXG8bvHtVEN8hwllT9mqgbJKuRhimOdNPl+TgpRvpt3Rw/FHjs20TPo95vByJtW5fv1Q8KZAxAS1l+SYk0Q9KMCiOazfTp+ZJj9R6KKtqcZ7rOFhBqAeD+72jUxwrFxNT2+mRkBE4JzDSTW/w9dgwMtNhIE5vup9XBpqmbCwuqXZ+vwJcvhRfxepshLjL7RDB9c9+RIvxMVn55BUHr5IyaOybgxaN5ZfRiHDYrb/NCl5VDHWaFslzTOWHeris4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
